language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: PkOZRGKCbptCwfhimIJbiytYq7hbjlOBz2TJhb7UZdeFXw7A+F020bek/qevCsAtmwLpuFEPfX4RH06zc4TswpJU5AhskVyEqMwmX3wyjj3uV6Ejn/XZTmIShc2EDFGH+hBcufcM9v+/8oGWu1Z1jMRo7+kzehcY/aJ9G0uznWbR6XBcOm7vSfgt0guA7G0Mk0PYJBnN4vlpXkheXrq1DUVA/VE0/IyJak5LaMj8uiX/jHJXn/3H2Ut+RcS7JIJR5Pqk/KLgCJtGTuXLNFrGG88qNjw+UuF4JVnwzJjhK6hCn1PtnZmmrCUhNI+GUXAxakmn320I/AJdFJGmJmhKsx5czrxBvb/5cvrInS6M+bdlmMK5vc82e2gYbO6kw62ChWZk1G6udj8tdPBUCB/T6B6EWHDbPkJL3YONjt2mOg4gk9rERQ2EJrFSjdatgSWjGXhe3axn8O8voSyKfieTpkO/DDlhIQl+gy6U3+DAYj5rOVlbf8v+vwKmlNzPxFGXAkLYCvweMX77euBYqPD3EueRnSkwd7Zb5sA68dWWEjvMb7U0HafSwAfQYm35/my9q5Qs5NiNpbliyLBeod7zOOJt3VZHgJepiQyFnLjeNvQWF99c58kofnFnsiTKVPyYE32QQ4O6Xma4H/7Sa9AxPNyYBsVKSrLuEW5Syj/+p3s=
  app: my-daily-dose
  on:
    repo: jpquense/daily-dose
